import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-slate-900`}
      >
        <div className="min-h-screen flex flex-col">
          <Header />
          <main className="flex-1 w-full">{children}</main>
          <footer className="border-t border-slate-200 bg-white/90">
            <div className="flex w-full items-center justify-between px-8 py-4 text-xs text-slate-500">
              <span>© 2025 FlexChartJS. All rights reserved.</span>
              <span className="flex items-center gap-4">
                <button className="hover:text-slate-800 transition-colors">
                  GitHub
                </button>
                <button className="hover:text-slate-800 transition-colors">
                  Docs
                </button>
                <button className="hover:text-slate-800 transition-colors">
                  Community
                </button>
              </span>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
